#  Geometry help:
#
#            | PMT|  
#            ------      ________ Upper Interface
#           /      \        
#          / Upper  \        
#         /  Guide   \      
#        /   Cone     \ 
#	     |	          |
#	     |   Middle   |
#	     |   Box      |
#	     |	          |  ________ Lower Interface
#        \            /
#         \  Lower   /		
#          \ Guide  /			
#           \Cone  /     ________ Quartz-LG interface plane
#            |    |
#            |    | Quartz
#            |    |
#    --->    |    |
#   Beam (Z) |_ __|
#
#               ^
#              / \  (y)
#               |
#  (x) into screen

/MainDet/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/MainDet/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/MainDet/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
/MainDet/LightGuideMiddleBox 300 mm			       #Height of box between upper and lower cones	
/MainDet/LightGuideUpperInterface 259 mm             #Distance between upper and lower interface planes
/MainDet/LightGuideQuartzInterfaceOpeningX 19.8 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/MainDet/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/MainDet/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm

/MainDet/QuartzSizeZ 20 mm
/MainDet/QuartzSizeX 190 mm
/MainDet/QuartzSizeY 60 mm                           #Without the 45 degree cut
/MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/MainDet/SetCenterPositionInX 0 mm
/MainDet/SetCenterPositionInY 145 mm
/MainDet/SetCenterPositionInZ 276.5 mm
/MainDet/YawRotation 0 deg                           #Rotates the detector about the y-axis
/MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
/MainDet/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/MainDet/UpdateGeometry

#------------------#Scintillator---------------#

/Gem1/SizeZ 3 mm                  
/Gem1/SizeX 100 mm                  
/Gem1/SizeY 200 mm                 
/Gem1/SetCenterPositionInX 0 mm            
/Gem1/SetCenterPositionInY -160 mm               
/Gem1/SetCenterPositionInZ 0 mm            
/Gem1/PolarRotation 0 deg                     #Rotates the Gemillator about the x-axis
/Gem1/AzimuthalRotation 90 deg                 #Rotates the Gemillator about the z-axis
/Gem1/UpdateGeometry

/Gem2/SizeZ 3 mm                  
/Gem2/SizeX 100 mm                  
/Gem2/SizeY 200 mm                 
/Gem2/SetCenterPositionInX 0 mm            
/Gem2/SetCenterPositionInY -160 mm               
/Gem2/SetCenterPositionInZ 159 mm            
/Gem2/PolarRotation 0 deg                     #Rotates the Gemillator about the x-axis
/Gem2/AzimuthalRotation 90 deg                 #Rotates the Gemillator about the z-axis
/Gem2/UpdateGeometry

/Gem3/SizeZ 3 mm                  
/Gem3/SizeX 100 mm                  
/Gem3/SizeY 200 mm                 
/Gem3/SetCenterPositionInX 0 mm            
/Gem3/SetCenterPositionInY -160 mm               
/Gem3/SetCenterPositionInZ 519 mm            
/Gem3/PolarRotation 0 deg                     #Rotates the Gemillator about the x-axis
/Gem3/AzimuthalRotation 90 deg                 #Rotates the Gemillator about the z-axis
/Gem3/UpdateGeometry

#------------------#Misc. Frame---------------#

#None exist for this setup. If you want to add like shielding or a plate, add it here

#------------------#Beam commands -----------------------#

/Generator/PrimaryParticle 2                      #Sets the primary particle type. 1 for electrons, 2 for muons, 3 for positrons
/Generator/EventHitRegion 6                       #Use hr=6 for this branch. Spawns particles at GEM1
/Generator/EventShift 0 mm                        #Use to move the spawning location of primary events. Set usage in MOLLEROptPrimaryGeneratorAction.cc
/Generator/SegmentHitPosX 0                       #Select a section of the segment to fire the beam at. Currently only works if EventHitRegion = 10
/Generator/SegmentHitPosY 0
/Generator/BeamSolidAngle 24                       #Units of degrees. Determines the angular spread of the beam from the z-axis with a cos^2 distribution. For Mainz was 0.0872665
/Generator/BeamTiltAngle 0                        #Tilts the beam away from the z-axis in units of degrees (rotation about the y-axis)
/Generator/BeamTiltDirection 90.0                 #Sets the direction of the tilt. 0 is the x-axis, 90 is the y-axis, etc. (rotation about z-axis)
/Generator/BeamEnergy 8000		                  #Units of MeV. Does nothing if PrimaryParticle != 1
/Generator/BeamEnergyCut 0                        #Units of MeV. Sets minimum energy for primary particles (less than or equal is rejected)

/Storage/DetectorFocus 1                        #Controls what data is saved to the ROOT Ntuple. 0 for everything, 1 for events hitting the MainDet, 999 saves nothing, etc.

/RunAction/SetID 2
/random/setSeeds 346082 823457
/vis/disable
/run/beamOn 100