/vis/open OGL 1280x800-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
#/vis/set/textColour green
#/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! Xen
#/vis/set/textLayout    # Revert to normal (left adjusted) layout
#/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of the event
#/vis/scene/add/date    # Date stamp
#/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
#
# Frame
#/vis/set/colour red
#/vis/set/lineWidth 2
#/vis/scene/add/frame   # Simple frame around the view
#/vis/set/colour        # Revert to default colour (white)
#/vis/set/lineWidth     # Revert to the default line width (1.)
#
# To get a nice view
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 100 150
#
# Re-establish auto-refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/control/verbose 0
# Increases display limit of photons 
/vis/ogl/set/displayListLimit 500000

#  Geometry help:
#
#            | PMT|  
#            ------      ________ Upper Interface
#           /      \        
#          / Upper  \        
#         /  Guide   \      
#        /   Cone     \ 
#	     |	          |
#	     |   Middle   |
#	     |   Box      |
#	     |	          |  ________ Lower Interface
#        \            /
#         \  Lower   /		
#          \ Guide  /			
#           \Cone  /     ________ Quartz-LG interface plane
#            |    |
#            |    | Quartz
#            |    |
#    --->    |    |
#   Beam (Z) |_ __|
#
#               ^
#              / \  (y)
#               |
#  (x) into screen

/MainDet/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/MainDet/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/MainDet/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
/MainDet/LightGuideMiddleBox 0.001 mm			       #Height of box between upper and lower cones	
/MainDet/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
/MainDet/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/MainDet/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/MainDet/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm

/MainDet/QuartzSizeZ 17 mm
/MainDet/QuartzSizeX 80 mm
/MainDet/QuartzSizeY 140 mm                          #Without the 45 degree cut
/MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/MainDet/SetCenterPositionInX 0 mm
/MainDet/SetCenterPositionInY 0 mm
/MainDet/SetCenterPositionInZ 0 mm
/MainDet/YawRotation 0 deg                           #Rotates the detector about the y-axis
/MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
/MainDet/AzimuthalRotation 0 deg                     #Rotates the detector about the z-axis

/MainDet/UpdateGeometry

#------------------#Scintillator---------------#

#None exist for this setup. If you need a scintillator, add it here

#------------------#Misc. Frame---------------#

#None exist for this setup. If you want to add like shielding or a plate, add it here

#------------------#Beam commands -----------------------#

/Generator/PrimaryParticle 1                      #Sets the primary particle type. 1 for electrons, 2 for muons
/Generator/EventHitRegion 2                       #1->8 = BF det centers 1-8, 9 = segment scan
/Generator/EventShift 0 mm                        #Use to move the spawning location of primary events. Set usage in MOLLEROptPrimaryGeneratorAction.cc
/Generator/SegmentHitPosX 0                       #Select a section of the segment to fire the beam at. Currently only works if EventHitRegion = 10
/Generator/SegmentHitPosY 0                       #The tile starts at 0.2
/Generator/BeamSolidAngle 0                       #Units of degrees. Determines the angular spread of the beam from the z-axis with a cos^2 distribution. For Mainz was 0.0872665
/Generator/BeamTiltAngle 0                      #Tilts the beam away from the z-axis in units of degrees (rotation about the y-axis)
/Generator/BeamTiltDirection 90.0                 #Sets the direction of the tilt. 0 is the x-axis, 90 is the y-axis, etc. (rotation about z-axis)
/Generator/BeamEnergy 8000		                  #Units of MeV. Does nothing if PrimaryParticle != 1
/Generator/BeamEnergyCut 0                        #Units of MeV. Sets minimum energy for primary particles (less than or equal is rejected)

/Storage/DetectorFocus 999                        #Controls what data is saved to the ROOT Ntuple. 0 for everything, 1 for events hitting the MainDet, 999 saves nothing, etc.

#/RunAction/SetID 3
#/random/setSeeds 346082 823457
#/run/beamOn 1