/vis/open OGL 1280x800-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
#/vis/set/textColour green
#/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! Xen
#/vis/set/textLayout    # Revert to normal (left adjusted) layout
#/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of the event
#/vis/scene/add/date    # Date stamp
#/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
#
# Frame
#/vis/set/colour red
#/vis/set/lineWidth 2
#/vis/scene/add/frame   # Simple frame around the view
#/vis/set/colour        # Revert to default colour (white)
#/vis/set/lineWidth     # Revert to the default line width (1.)
#
# To get a nice view
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 100 150
#
# Re-establish auto-refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/control/verbose 0
# Increases display limit of photons 
/vis/ogl/set/displayListLimit 500000

#  Geometry help:
#
#            | PMT|  
#            ------      ________ Upper Interface
#           /      \        
#          / Upper  \        
#         /  Guide   \      
#        /   Cone     \ 
#	     |	          |
#	     |   Middle   |
#	     |   Box      |
#	     |	          |  ________ Lower Interface
#        \            /
#         \  Lower   /		
#          \ Guide  /			
#           \Cone  /     ________ Quartz-LG interface plane
#            |    |
#            |    | Quartz
#            |    |
#    --->    |    |
#   Beam (Z) |_ __|
#
#               ^
#              / \  (y)
#               |
#  (x) into screen

/ShowerMax/LightGuideLowerConeBackAngle 12.9 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/ShowerMax/LightGuideLowerConeFrontAngle 12.9 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/ShowerMax/LightGuideLowerInterface 67.462 mm              #Distance between quartz-LG interface and lower interface plane
/ShowerMax/LightGuideMiddleBox 0.01 mm			     #Height of box between upper and lower cones. Remove for showermax
/ShowerMax/LightGuideUpperInterface 250.52 mm             #Distance between upper and lower interface planes (Det height - MiddleBox)
/ShowerMax/LightGuideQuartzInterfaceOpeningX 26.6 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/ShowerMax/LightGuideQuartzInterfaceOpeningZ 5.496 cm    #But larger, according to the CAD model (1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/ShowerMax/LightGuideQuartzToPMTOffset 0 mm            #offset of PMT along Z w.r.t quartz to center light on cathode
/ShowerMax/LightGuidePMTInterfaceOpeningX 26.6 cm       #These should stay fixed - set by the PMT size 
/ShowerMax/LightGuidePMTInterfaceOpeningZ 7.0 cm

/ShowerMax/QuartzSizeZ 6 mm
/ShowerMax/QuartzSizeX 265 mm
/ShowerMax/QuartzSizeY 160 mm                          #Without the 45 degree cut

/ShowerMax/TungstenSizeX 265 mm
/ShowerMax/TungstenSizeY 160 mm
/ShowerMax/TungstenSizeZ 8 mm

/ShowerMax/QuartzRotX 0 deg                           #rotate the quartz & tungsten w.r.t. the light guide. Not working in this branch atm

/ShowerMax/SetCenterPositionInX 0 mm
/ShowerMax/SetCenterPositionInY 0 mm
/ShowerMax/SetCenterPositionInZ 0 mm
/ShowerMax/YawRotation 0 deg                           #Rotates the detector about the y-axis
/ShowerMax/PolarRotation 0 deg                         #counter rotate the detector as a whole about the x-axis
/ShowerMax/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/ShowerMax/UpdateGeometry

#------------------#Scintillator---------------#

/Scint1/SizeZ 25.4 mm                  
/Scint1/SizeX 305 mm                  
/Scint1/SizeY 305 mm                 
/Scint1/SetCenterPositionInX 0 mm            
/Scint1/SetCenterPositionInY 0.8 mm           #-82.5 is ~ start of stack    
/Scint1/SetCenterPositionInZ -919 mm            
/Scint1/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint1/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint1/UpdateGeometry

/Scint2/SizeZ 7 mm                  
/Scint2/SizeX 200 mm                  
/Scint2/SizeY 70 mm                 
/Scint2/SetCenterPositionInX 0 mm            
/Scint2/SetCenterPositionInY -116.7 mm            #-200 is ~ start of stack     
/Scint2/SetCenterPositionInZ -40 mm            
/Scint2/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint2/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint2/UpdateGeometry

/Scint3/SizeZ 25.4 mm                  
/Scint3/SizeX 305 mm                  
/Scint3/SizeY 305 mm                 
/Scint3/SetCenterPositionInX 0 mm            
/Scint3/SetCenterPositionInY 15.8 mm           #-82.5 is ~ start of stack    
/Scint3/SetCenterPositionInZ 794 mm            
/Scint3/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint3/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint3/UpdateGeometry

#------------------#Beam commands -----------------------#

/Generator/PrimaryParticle 1                      #Sets the primary particle type. 1 for electrons, 2 for muons, 3 for positrons
/Generator/EventHitRegion 2                       #1 = center, 2 = controlled position, 3 = Mainz, 4-5 = HallD?
/Generator/EventShift 0 mm                        #Use to move the spawning location of primary events. Set usage in MOLLEROptPrimaryGeneratorAction.cc
/Generator/SegmentHitPosX 0                       #Select a section of the segment to fire the beam at. Currently only works if EventHitRegion = 10
/Generator/SegmentHitPosY 128                       #Tile starts at ~ 0.5mm
/Generator/BeamSolidAngle 14                       #Units of degrees. Determines the angular spread of the beam from the z-axis with a cos^2 distribution. For Mainz was 0.0872665
/Generator/BeamTiltAngle 0                        #Tilts the beam away from the z-axis in units of degrees (rotation about the y-axis)
/Generator/BeamTiltDirection 90.0                 #Sets the direction of the tilt. 0 is the x-axis, 90 is the y-axis, etc. (rotation about z-axis)
/Generator/BeamEnergy 8000		                  #Units of MeV. Does nothing if PrimaryParticle != 1
/Generator/BeamEnergyCut 0                        #Units of MeV. Sets minimum energy for primary particles (less than or equal is rejected)

/Storage/DetectorFocus 999                        #Controls what data is saved to the ROOT Ntuple. 0 for everything, 1 for events hitting the ShowerMax, 999 saves nothing, etc.

#/RunAction/SetID 3
#/random/setSeeds 346082 823457
#/run/beamOn 1