#  Geometry help:
#
#            | PMT|  
#            ------      ________ Upper Interface
#           /      \        
#          / Upper  \        
#         /  Guide   \      
#        /   Cone     \ 
#	     |	          |
#	     |   Middle   |
#	     |   Box      |
#	     |	          |  ________ Lower Interface
#        \            /
#         \  Lower   /		
#          \ Guide  /			
#           \Cone  /     ________ Quartz-LG interface plane
#            |    |
#            |    | Quartz
#            |    |
#    --->    |    |
#   Beam (Z) |_ __|
#
#               ^
#              / \  (y)
#               |
#  (x) into screen

#------------------#Ring 1--------------------#
if (Detector == 1){

    /MainDet/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
    /MainDet/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
    /MainDet/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
    /MainDet/LightGuideMiddleBox 410 mm			       #Height of box between upper and lower cones	
    /MainDet/LightGuideUpperInterface 251 mm             #Distance between upper and lower interface planes
    /MainDet/LightGuideQuartzInterfaceOpeningX 17.7 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
    /MainDet/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
    /MainDet/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
    /MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
    /MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm       #

    /MainDet/QuartzSizeZ 20 mm
    /MainDet/QuartzSizeX 169 mm
    /MainDet/QuartzSizeY 20 mm                           #Without the 45 degree cut
    /MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

    /MainDet/SetCenterPositionInX 0 mm
    /MainDet/SetCenterPositionInY 270.7 mm              #When placing modules, the change in position due to PolarRotation != 0 must be done by hand
    /MainDet/SetCenterPositionInZ 1923.4 mm             #Annoying, but can be done. Use rotation matrix about X-axis
    /MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
    /MainDet/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

    /MainDet/UpdateGeometry

}
#------------------#Ring 2--------------------#
if (Detector == 2){

    /MainDet/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
    /MainDet/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
    /MainDet/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
    /MainDet/LightGuideMiddleBox 400 mm			       #Height of box between upper and lower cones	
    /MainDet/LightGuideUpperInterface 205 mm             #Distance between upper and lower interface planes
    /MainDet/LightGuideQuartzInterfaceOpeningX 18.7 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
    /MainDet/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
    /MainDet/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
    /MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
    /MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm

    /MainDet/QuartzSizeZ 20 mm
    /MainDet/QuartzSizeX 179 mm
    /MainDet/QuartzSizeY 60 mm                           #Without the 45 degree cut
    /MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

    /MainDet/SetCenterPositionInX 0 mm
    /MainDet/SetCenterPositionInY 292.8 mm
    /MainDet/SetCenterPositionInZ 1645.60 mm
    /MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
    /MainDet/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

    /MainDet/UpdateGeometry

}
#------------------#Ring 3--------------------#
if (Detector == 3){

    /MainDet/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
    /MainDet/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
    /MainDet/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
    /MainDet/LightGuideMiddleBox 300 mm			       #Height of box between upper and lower cones	
    /MainDet/LightGuideUpperInterface 259 mm             #Distance between upper and lower interface planes
    /MainDet/LightGuideQuartzInterfaceOpeningX 19.8 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
    /MainDet/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
    /MainDet/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
    /MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
    /MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm

    /MainDet/QuartzSizeZ 20 mm
    /MainDet/QuartzSizeX 190 mm
    /MainDet/QuartzSizeY 60 mm                           #Without the 45 degree cut
    /MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

    /MainDet/SetCenterPositionInX 0 mm
    /MainDet/SetCenterPositionInY 329.8 mm
    /MainDet/SetCenterPositionInZ 1371.51 mm
    /MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
    /MainDet/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

    /MainDet/UpdateGeometry

}
#------------------#Ring 4--------------------#
if (Detector == 4){

    /MainDet/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
    /MainDet/LightGuideLowerConeFrontAngle 17 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
    /MainDet/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
    /MainDet/LightGuideMiddleBox 200 mm			       #Height of box between upper and lower cones	
    /MainDet/LightGuideUpperInterface 253 mm             #Distance between upper and lower interface planes
    /MainDet/LightGuideQuartzInterfaceOpeningX 22.1 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
    /MainDet/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
    /MainDet/LightGuideQuartzToPMTOffset 3 mm            #offset of PMT along Z w.r.t quartz to center light on cathode
    /MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
    /MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm

    /MainDet/QuartzSizeZ 20 mm
    /MainDet/QuartzSizeX 213 mm
    /MainDet/QuartzSizeY 120 mm                          #Without the 45 degree cut
    /MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

    /MainDet/SetCenterPositionInX 0 mm
    /MainDet/SetCenterPositionInY 366.9 mm
    /MainDet/SetCenterPositionInZ 1092.08 mm
    /MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
    /MainDet/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

    /MainDet/UpdateGeometry

}
#------------------#Ring 5 FF--------------------# 
if (Detector == 5){

    /MainDet/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
    /MainDet/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
    /MainDet/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
    /MainDet/LightGuideMiddleBox 0.001 mm			       #Height of box between upper and lower cones	
    /MainDet/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
    /MainDet/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
    /MainDet/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
    /MainDet/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
    /MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
    /MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm

    /MainDet/QuartzSizeZ 17 mm
    /MainDet/QuartzSizeX 80 mm
    /MainDet/QuartzSizeY 140 mm                          #Without the 45 degree cut
    /MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

    /MainDet/SetCenterPositionInX 0 mm
    /MainDet/SetCenterPositionInY 435.3 mm
    /MainDet/SetCenterPositionInZ 651.64 mm
    /MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
    /MainDet/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

    /MainDet/UpdateGeometry

}
#------------------#Ring 5 BF1--------------------#
if (Detector == 6){

    /MainDet/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
    /MainDet/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
    /MainDet/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
    /MainDet/LightGuideMiddleBox 0.001 mm			       #Height of box between upper and lower cones	
    /MainDet/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
    /MainDet/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
    /MainDet/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
    /MainDet/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
    /MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
    /MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm

    /MainDet/QuartzSizeZ 17 mm
    /MainDet/QuartzSizeX 80 mm
    /MainDet/QuartzSizeY 140 mm                          #Without the 45 degree cut
    /MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

    /MainDet/SetCenterPositionInX -86.7 mm              #-86.7 when about the origin, -239.7 in the BF segment (shifted by -250 mm)
    /MainDet/SetCenterPositionInY 427.4 mm
    /MainDet/SetCenterPositionInZ 802.47 mm
    /MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
    /MainDet/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

    /MainDet/UpdateGeometry

}
#------------------#Ring 5 BF2--------------------#
if (Detector == 7){

    /MainDet/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
    /MainDet/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
    /MainDet/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
    /MainDet/LightGuideMiddleBox 0.001 mm			       #Height of box between upper and lower cones	
    /MainDet/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
    /MainDet/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
    /MainDet/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
    /MainDet/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
    /MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
    /MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm

    /MainDet/QuartzSizeZ 17 mm
    /MainDet/QuartzSizeX 80 mm
    /MainDet/QuartzSizeY 140 mm                          #Without the 45 degree cut
    /MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

    /MainDet/SetCenterPositionInX 86.7 mm               #86.7 when about the origin, -66.3 in the BF segment (shifted by -250 mm)
    /MainDet/SetCenterPositionInY 427.4 mm
    /MainDet/SetCenterPositionInZ 802.47 mm
    /MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
    /MainDet/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

    /MainDet/UpdateGeometry

}
#------------------#Ring 6--------------------#
if (run == 8){

    /MainDet/LightGuideLowerConeBackAngle 20 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
    /MainDet/LightGuideLowerConeFrontAngle 17 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
    /MainDet/LightGuideLowerInterface 83 mm              #Distance between quartz-LG interface and lower interface plane
    /MainDet/LightGuideMiddleBox 90 mm			       #Height of box between upper and lower cones	
    /MainDet/LightGuideUpperInterface 163 mm             #Distance between upper and lower interface planes
    /MainDet/LightGuideQuartzInterfaceOpeningX 26.8 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
    /MainDet/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model (1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
    /MainDet/LightGuideQuartzToPMTOffset 0 mm            #offset of PMT along Z w.r.t quartz to center light on cathode
    /MainDet/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
    /MainDet/LightGuidePMTInterfaceOpeningZ 7.0 cm

    /MainDet/QuartzSizeZ 20 mm
    /MainDet/QuartzSizeX 260 mm
    /MainDet/QuartzSizeY 100 mm                          #Without the 45 degree cut
    /MainDet/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

    /MainDet/SetCenterPositionInX 0 mm
    /MainDet/SetCenterPositionInY 517 mm
    /MainDet/SetCenterPositionInZ 501.78 mm
    /MainDet/PolarRotation 3 deg                         #counter rotate the detector as a whole about the x-axis
    /MainDet/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

    /MainDet/UpdateGeometry

}
#------------------#Scintillator---------------#

#None exist for this setup. If you need a scintillator, add it here

#------------------#Misc. Frame---------------#

#None exist for this setup. If you want to add like shielding or a plate, add it here

#------------------#Beam commands -----------------------#

/Generator/PrimaryParticle 3                      #Sets the primary particle type. 1 for electrons, 2 for muons
/Generator/EventHitRegion 1                       #1->8 = BF det centers 1-8, 9 = segment scan
/Generator/EventShift 0 mm                        #Use to move the spawning location of primary events. Set usage in MOLLEROptPrimaryGeneratorAction.cc
/Generator/SegmentHitPosX 0                       #Select a section of the segment to fire the beam at. Currently only works if EventHitRegion = 10
/Generator/SegmentHitPosY 0
/Generator/BeamSolidAngle 0                       #Units of degrees. Determines the angular spread of the beam from the z-axis with a cos^2 distribution. For Mainz was 0.0872665
/Generator/BeamTiltAngle 0                        #Tilts the beam away from the z-axis in units of degrees (rotation about the y-axis)
/Generator/BeamTiltDirection 90.0                 #Sets the direction of the tilt. 0 is the x-axis, 90 is the y-axis, etc. (rotation about z-axis)
/Generator/BeamEnergy 5000		                  #Units of MeV. Does nothing if PrimaryParticle != 1
/Generator/BeamEnergyCut 0                        #Units of MeV. Sets minimum energy for primary particles (less than or equal is rejected)

/Storage/DetectorFocus 999                        #Controls what data is saved to the ROOT Ntuple. 0 for everything, 1 for events hitting the MainDet, 999 saves nothing, etc.

/RunAction/SetID 2
/random/setSeeds 346082 823457
/vis/disable
/run/beamOn 100