/vis/open OGL 1280x800-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
#/vis/set/textColour green
#/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! Xen
#/vis/set/textLayout    # Revert to normal (left adjusted) layout
#/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of the event
#/vis/scene/add/date    # Date stamp
#/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
#
# Frame
#/vis/set/colour red
#/vis/set/lineWidth 2
#/vis/scene/add/frame   # Simple frame around the view
#/vis/set/colour        # Revert to default colour (white)
#/vis/set/lineWidth     # Revert to the default line width (1.)
#
# To get a nice view
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 100 150
#
# Re-establish auto-refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/control/verbose 0
# Increases display limit of photons 
/vis/ogl/set/displayListLimit 500000

#  Geometry help:
#
#            | PMT|  
#            ------      ________ Upper Interface
#           /      \        
#          / Upper  \        
#         /  Guide   \      
#        /   Cone     \ 
#	     |	          |
#	     |   Middle   |
#	     |   Box      |
#	     |	          |  ________ Lower Interface
#        \            /
#         \  Lower   /		
#          \ Guide  /			
#           \Cone  /     ________ Quartz-LG interface plane
#            |    |
#            |    | Quartz
#            |    |
#    --->    |    |
#   Beam (Z) |_ __|
#
#               ^
#              / \  (y)
#               |
#  (x) into screen

#  The below parameters are for the front flush segment

#------------------#BF Segment commands --------------------#

#------------------#Ring 1 commands --------------------#

/Ring1/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring1/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring1/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
/Ring1/LightGuideMiddleBox 410 mm			       #Height of box between upper and lower cones	
/Ring1/LightGuideUpperInterface 251 mm             #Distance between upper and lower interface planes
/Ring1/LightGuideQuartzInterfaceOpeningX 17.7 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring1/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring1/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring1/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring1/LightGuidePMTInterfaceOpeningZ 7.0 cm       #

/Ring1/QuartzSizeZ 20 mm
/Ring1/QuartzSizeX 169 mm
/Ring1/QuartzSizeY 20 mm                           #Without the 45 degree cut
/Ring1/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring1/SetCenterPositionInX -250 mm
/Ring1/SetCenterPositionInY 263 mm
/Ring1/SetCenterPositionInZ 1923.94 mm
/Ring1/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring1/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/Ring1/UpdateGeometry

#------------------#Ring 2 commands --------------------#

/Ring2/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring2/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring2/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
/Ring2/LightGuideMiddleBox 400 mm			       #Height of box between upper and lower cones	
/Ring2/LightGuideUpperInterface 205 mm             #Distance between upper and lower interface planes
/Ring2/LightGuideQuartzInterfaceOpeningX 18.7 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring2/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring2/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring2/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring2/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring2/QuartzSizeZ 20 mm
/Ring2/QuartzSizeX 179 mm
/Ring2/QuartzSizeY 60 mm                           #Without the 45 degree cut
/Ring2/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring2/SetCenterPositionInX -250 mm
/Ring2/SetCenterPositionInY 285.0 mm
/Ring2/SetCenterPositionInZ 1645.60 mm
/Ring2/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring2/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/Ring2/UpdateGeometry

#------------------#Ring 3 commands --------------------#

/Ring3/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring3/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring3/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
/Ring3/LightGuideMiddleBox 300 mm			       #Height of box between upper and lower cones	
/Ring3/LightGuideUpperInterface 259 mm             #Distance between upper and lower interface planes
/Ring3/LightGuideQuartzInterfaceOpeningX 19.8 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring3/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring3/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring3/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring3/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring3/QuartzSizeZ 20 mm
/Ring3/QuartzSizeX 190 mm
/Ring3/QuartzSizeY 60 mm                           #Without the 45 degree cut
/Ring3/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring3/SetCenterPositionInX -250 mm
/Ring3/SetCenterPositionInY 322.1 mm
/Ring3/SetCenterPositionInZ 1371.51 mm
/Ring3/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring3/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/Ring3/UpdateGeometry

#------------------#Ring 4 commands --------------------#

/Ring4/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring4/LightGuideLowerConeFrontAngle 17 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring4/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
/Ring4/LightGuideMiddleBox 200 mm			       #Height of box between upper and lower cones	
/Ring4/LightGuideUpperInterface 253 mm             #Distance between upper and lower interface planes
/Ring4/LightGuideQuartzInterfaceOpeningX 22.1 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring4/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring4/LightGuideQuartzToPMTOffset 3 mm            #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring4/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring4/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring4/QuartzSizeZ 20 mm
/Ring4/QuartzSizeX 213 mm
/Ring4/QuartzSizeY 120 mm                          #Without the 45 degree cut
/Ring4/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring4/SetCenterPositionInX -250 mm
/Ring4/SetCenterPositionInY 359.3 mm
/Ring4/SetCenterPositionInZ 1092.08 mm
/Ring4/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring4/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/Ring4/UpdateGeometry

#------------------#Ring 5 FF commands --------------------# 

/Ring5/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring5/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring5/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
/Ring5/LightGuideMiddleBox 0.001 mm			       #Height of box between upper and lower cones	
/Ring5/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
/Ring5/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring5/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring5/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring5/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring5/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring5/QuartzSizeZ 17 mm
/Ring5/QuartzSizeX 80 mm
/Ring5/QuartzSizeY 140 mm                          #Without the 45 degree cut
/Ring5/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring5/SetCenterPositionInX -250 mm
/Ring5/SetCenterPositionInY 427.7 mm
/Ring5/SetCenterPositionInZ 651.64 mm
/Ring5/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring5/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/Ring5/UpdateGeometry

#------------------#Ring 5 BF1 commands --------------------#

/Ring6/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring6/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring6/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
/Ring6/LightGuideMiddleBox 0.001 mm			       #Height of box between upper and lower cones	
/Ring6/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
/Ring6/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring6/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring6/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring6/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring6/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring6/QuartzSizeZ 17 mm
/Ring6/QuartzSizeX 80 mm
/Ring6/QuartzSizeY 140 mm                          #Without the 45 degree cut
/Ring6/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring6/SetCenterPositionInX -336.7 mm              #-86.7 when about the origin, -239.7 in the BF segment (shifted by -250 mm)
/Ring6/SetCenterPositionInY 427.7 mm
/Ring6/SetCenterPositionInZ 802.47 mm
/Ring6/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring6/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/Ring6/UpdateGeometry

#------------------#Ring 5 BF2 commands --------------------#

/Ring7/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring7/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring7/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
/Ring7/LightGuideMiddleBox 0.001 mm			       #Height of box between upper and lower cones	
/Ring7/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
/Ring7/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring7/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring7/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring7/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring7/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring7/QuartzSizeZ 17 mm
/Ring7/QuartzSizeX 80 mm
/Ring7/QuartzSizeY 140 mm                          #Without the 45 degree cut
/Ring7/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring7/SetCenterPositionInX -163.3 mm               #86.7 when about the origin, -66.3 in the BF segment (shifted by -250 mm)
/Ring7/SetCenterPositionInY 427.7 mm
/Ring7/SetCenterPositionInZ 802.47 mm
/Ring7/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring7/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/Ring7/UpdateGeometry

#------------------#Ring 6 commands --------------------#

/Ring8/LightGuideLowerConeBackAngle 20 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring8/LightGuideLowerConeFrontAngle 17 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring8/LightGuideLowerInterface 83 mm              #Distance between quartz-LG interface and lower interface plane
/Ring8/LightGuideMiddleBox 90 mm			       #Height of box between upper and lower cones	
/Ring8/LightGuideUpperInterface 163 mm             #Distance between upper and lower interface planes
/Ring8/LightGuideQuartzInterfaceOpeningX 26.8 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring8/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model (1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring8/LightGuideQuartzToPMTOffset 0 mm            #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring8/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring8/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring8/QuartzSizeZ 20 mm
/Ring8/QuartzSizeX 260 mm
/Ring8/QuartzSizeY 100 mm                          #Without the 45 degree cut
/Ring8/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring8/SetCenterPositionInX -250 mm
/Ring8/SetCenterPositionInY 509.3 mm
/Ring8/SetCenterPositionInZ 501.78 mm
/Ring8/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring8/AzimuthalRotation 0 deg                 #Rotates the detector about the z-axis

/Ring8/UpdateGeometry

#------------------#FF Segment commands --------------------#

#------------------#Ring 1 commands --------------------#

/Ring9/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring9/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring9/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
/Ring9/LightGuideMiddleBox 410 mm			       #Height of box between upper and lower cones	
/Ring9/LightGuideUpperInterface 251 mm             #Distance between upper and lower interface planes
/Ring9/LightGuideQuartzInterfaceOpeningX 17.7 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring9/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring9/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring9/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring9/LightGuidePMTInterfaceOpeningZ 7.0 cm       #

/Ring9/QuartzSizeZ 20 mm
/Ring9/QuartzSizeX 169 mm
/Ring9/QuartzSizeY 20 mm                           #Without the 45 degree cut
/Ring9/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring9/SetCenterPositionInX 250 mm
/Ring9/SetCenterPositionInY 263 mm
/Ring9/SetCenterPositionInZ 1773.11 mm
/Ring9/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring9/AzimuthalRotation 0 deg                  #Rotates the detector about the z-axis

/Ring9/UpdateGeometry

#------------------#Ring 2 commands --------------------#

/Ring10/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring10/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring10/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
/Ring10/LightGuideMiddleBox 400 mm			        #Height of box between upper and lower cones	
/Ring10/LightGuideUpperInterface 205 mm             #Distance between upper and lower interface planes
/Ring10/LightGuideQuartzInterfaceOpeningX 18.7 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring10/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring10/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring10/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring10/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring10/QuartzSizeZ 20 mm
/Ring10/QuartzSizeX 179 mm
/Ring10/QuartzSizeY 60 mm                           #Without the 45 degree cut
/Ring10/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring10/SetCenterPositionInX 250 mm
/Ring10/SetCenterPositionInY 285.0 mm
/Ring10/SetCenterPositionInZ 1494.77 mm
/Ring10/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring10/AzimuthalRotation 0 deg                  #Rotates the detector about the z-axis

/Ring10/UpdateGeometry

#------------------#Ring 3 commands --------------------#

/Ring11/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring11/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring11/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
/Ring11/LightGuideMiddleBox 300 mm			        #Height of box between upper and lower cones	
/Ring11/LightGuideUpperInterface 259 mm             #Distance between upper and lower interface planes
/Ring11/LightGuideQuartzInterfaceOpeningX 19.8 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring11/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring11/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring11/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring11/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring11/QuartzSizeZ 20 mm
/Ring11/QuartzSizeX 190 mm
/Ring11/QuartzSizeY 60 mm                           #Without the 45 degree cut
/Ring11/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring11/SetCenterPositionInX 250 mm
/Ring11/SetCenterPositionInY 322.1 mm
/Ring11/SetCenterPositionInZ 1220.68 mm
/Ring11/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring11/AzimuthalRotation 0 deg                  #Rotates the detector about the z-axis

/Ring11/UpdateGeometry

#------------------#Ring 4 commands --------------------#

/Ring12/LightGuideLowerConeBackAngle 22 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring12/LightGuideLowerConeFrontAngle 17 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring12/LightGuideLowerInterface 75 mm              #Distance between quartz-LG interface and lower interface plane
/Ring12/LightGuideMiddleBox 200 mm			        #Height of box between upper and lower cones	
/Ring12/LightGuideUpperInterface 253 mm             #Distance between upper and lower interface planes
/Ring12/LightGuideQuartzInterfaceOpeningX 22.1 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring12/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring12/LightGuideQuartzToPMTOffset 3 mm            #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring12/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring12/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring12/QuartzSizeZ 20 mm
/Ring12/QuartzSizeX 213 mm
/Ring12/QuartzSizeY 120 mm                          #Without the 45 degree cut
/Ring12/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring12/SetCenterPositionInX 250 mm
/Ring12/SetCenterPositionInY 359.3 mm
/Ring12/SetCenterPositionInZ 941.25 mm
/Ring12/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring12/AzimuthalRotation 0 deg                  #Rotates the detector about the z-axis

/Ring12/UpdateGeometry

#------------------#Ring 5 BF commands --------------------# 

/Ring13/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring13/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring13/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
/Ring13/LightGuideMiddleBox 0.001 mm			    #Height of box between upper and lower cones	
/Ring13/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
/Ring13/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring13/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring13/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring13/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring13/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring13/QuartzSizeZ 17 mm
/Ring13/QuartzSizeX 80 mm
/Ring13/QuartzSizeY 140 mm                          #Without the 45 degree cut
/Ring13/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring13/SetCenterPositionInX 250 mm
/Ring13/SetCenterPositionInY 427.7 mm
/Ring13/SetCenterPositionInZ 802.47 mm
/Ring13/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring13/AzimuthalRotation 0 deg                  #Rotates the detector about the z-axis

/Ring13/UpdateGeometry

#------------------#Ring 5 FF1 commands --------------------#

/Ring14/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring14/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring14/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
/Ring14/LightGuideMiddleBox 0.001 mm			    #Height of box between upper and lower cones	
/Ring14/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
/Ring14/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring14/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring14/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring14/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring14/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring14/QuartzSizeZ 17 mm
/Ring14/QuartzSizeX 80 mm
/Ring14/QuartzSizeY 140 mm                          #Without the 45 degree cut
/Ring14/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring14/SetCenterPositionInX 163.3 mm                 #-86.7 when about the origin, 66.3 in the FF segment (shifted by +250 mm)
/Ring14/SetCenterPositionInY 427.7 mm
/Ring14/SetCenterPositionInZ 651.64 mm
/Ring14/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring14/AzimuthalRotation 0 deg                  #Rotates the detector about the z-axis

/Ring14/UpdateGeometry

#------------------#Ring 5 FF2 commands --------------------#

/Ring15/LightGuideLowerConeBackAngle 19 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring15/LightGuideLowerConeFrontAngle 18 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring15/LightGuideLowerInterface 90 mm              #Distance between quartz-LG interface and lower interface plane
/Ring15/LightGuideMiddleBox 0.001 mm			    #Height of box between upper and lower cones	
/Ring15/LightGuideUpperInterface 329.5 mm           #Distance between upper and lower interface planes
/Ring15/LightGuideQuartzInterfaceOpeningX 8.8 cm    #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring15/LightGuideQuartzInterfaceOpeningZ 2.4 cm    #But larger, according to the CAD model  (it's 1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring15/LightGuideQuartzToPMTOffset -2 mm           #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring15/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring15/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring15/QuartzSizeZ 17 mm
/Ring15/QuartzSizeX 80 mm
/Ring15/QuartzSizeY 140 mm                          #Without the 45 degree cut
/Ring15/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring15/SetCenterPositionInX 336.7 mm               #86.7 when about the origin, 239.7 in the FF segment (shifted by +250 mm)
/Ring15/SetCenterPositionInY 427.7 mm
/Ring15/SetCenterPositionInZ 651.64 mm
/Ring15/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring15/AzimuthalRotation 0 deg                  #Rotates the detector about the z-axis

/Ring15/UpdateGeometry

#------------------#Ring 6 commands --------------------#

/Ring16/LightGuideLowerConeBackAngle 20 deg         #Angle between positive y-axis (length of quartz) and the downstream lower cone surface 
/Ring16/LightGuideLowerConeFrontAngle 17 deg        #Angle between positive y-axis (length of quartz) and the upstream lower cone surface
/Ring16/LightGuideLowerInterface 83 mm              #Distance between quartz-LG interface and lower interface plane
/Ring16/LightGuideMiddleBox 90 mm			        #Height of box between upper and lower cones	
/Ring16/LightGuideUpperInterface 163 mm             #Distance between upper and lower interface planes
/Ring16/LightGuideQuartzInterfaceOpeningX 26.8 cm   #These should be set according to the quartz size (always add 8 mm to quartz width ) (+0.8 disabled for Mainz beam test. Will return after)
/Ring16/LightGuideQuartzInterfaceOpeningZ 2.7 cm    #But larger, according to the CAD model (1.7 cm for 1 cm thick quartz and 2.2 cm for 1.5 cm thick quartz) (+0.7 disabled for Mainz test. Will return after)
/Ring16/LightGuideQuartzToPMTOffset 0 mm            #offset of PMT along Z w.r.t quartz to center light on cathode
/Ring16/LightGuidePMTInterfaceOpeningX 7.0 cm       #These should stay fixed - set by the PMT size 
/Ring16/LightGuidePMTInterfaceOpeningZ 7.0 cm

/Ring16/QuartzSizeZ 20 mm
/Ring16/QuartzSizeX 260 mm
/Ring16/QuartzSizeY 100 mm                          #Without the 45 degree cut
/Ring16/QuartzRotX -3 deg                           #rotate the quartz w.r.t. the light guide

/Ring16/SetCenterPositionInX 250 mm
/Ring16/SetCenterPositionInY 509.3 mm
/Ring16/SetCenterPositionInZ 350.95 mm
/Ring16/PolarRotation 6 deg                         #counter rotate the detector as a whole about the x-axis
/Ring16/AzimuthalRotation 0 deg                  #Rotates the detector about the z-axis

/Ring16/UpdateGeometry

#------------------#Scintillator commands ---------------#

/Scint1/SizeZ 20 mm                  
/Scint1/SizeX 300 mm                  
/Scint1/SizeY 250 mm                 
/Scint1/SetCenterPositionInX -250 mm            
/Scint1/SetCenterPositionInY 0 mm        
/Scint1/SetCenterPositionInZ 70 mm            
/Scint1/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint1/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint1/UpdateGeometry

/Scint2/SizeZ 20 mm                  
/Scint2/SizeX 300 mm                   
/Scint2/SizeY 250 mm                  
/Scint2/SetCenterPositionInX -250 mm            
/Scint2/SetCenterPositionInY 250 mm           
/Scint2/SetCenterPositionInZ 70 mm    
/Scint2/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint2/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint2/UpdateGeometry

/Scint3/SizeZ 20 mm                  
/Scint3/SizeX 300 mm                  
/Scint3/SizeY 250 mm                  
/Scint3/SetCenterPositionInX -250 mm            
/Scint3/SetCenterPositionInY 0 mm        
/Scint3/SetCenterPositionInZ 2060 mm            
/Scint3/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint3/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint3/UpdateGeometry

/Scint4/SizeZ 20 mm                  
/Scint4/SizeX 300 mm                  
/Scint4/SizeY 250 mm                  
/Scint4/SetCenterPositionInX -250 mm            
/Scint4/SetCenterPositionInY 250 mm        
/Scint4/SetCenterPositionInZ 2060 mm 
/Scint4/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint4/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint4/UpdateGeometry

/Scint5/SizeZ 20 mm                  
/Scint5/SizeX 300 mm                  
/Scint5/SizeY 250 mm                 
/Scint5/SetCenterPositionInX 250 mm            
/Scint5/SetCenterPositionInY 0 mm        
/Scint5/SetCenterPositionInZ 70 mm            
/Scint5/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint5/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint5/UpdateGeometry

/Scint6/SizeZ 20 mm                  
/Scint6/SizeX 300 mm                   
/Scint6/SizeY 250 mm                  
/Scint6/SetCenterPositionInX 250 mm            
/Scint6/SetCenterPositionInY 250 mm           
/Scint6/SetCenterPositionInZ 70 mm    
/Scint6/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint6/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint6/UpdateGeometry

/Scint7/SizeZ 20 mm                  
/Scint7/SizeX 300 mm                  
/Scint7/SizeY 250 mm                  
/Scint7/SetCenterPositionInX 250 mm            
/Scint7/SetCenterPositionInY 0 mm        
/Scint7/SetCenterPositionInZ 2060 mm            
/Scint7/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint7/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint7/UpdateGeometry

/Scint8/SizeZ 20 mm                  
/Scint8/SizeX 300 mm                  
/Scint8/SizeY 250 mm                  
/Scint8/SetCenterPositionInX 250 mm            
/Scint8/SetCenterPositionInY 250 mm        
/Scint8/SetCenterPositionInZ 2060 mm 
/Scint8/PolarRotation 0 deg                     #Rotates the Scintillator about the x-axis
/Scint8/AzimuthalRotation 0 deg                 #Rotates the Scintillator about the z-axis
/Scint8/UpdateGeometry

#------------------#Misc. Frame commands ---------------#

/AlPlate/SizeZ 6.35 mm                  
/AlPlate/SizeX 1 mm                  
/AlPlate/SizeY 1 mm                  
/AlPlate/SetCenterPositionInX 700 mm            
/AlPlate/SetCenterPositionInY 700 mm        
/AlPlate/SetCenterPositionInZ 100 mm     
/AlPlate/PolarRotation 0 deg                     #Rotates the Plate about the x-axis
/AlPlate/AzimuthalRotation 0 deg                 #Rotates the Plate about the z-axis

/AlPlate/UpdateGeometry

#------------------#Beam commands -----------------------#

/Generator/PrimaryParticle 1                      #Sets the primary particle type. 1 for electrons, 2 for muons
/Generator/EventHitRegion 17                       #1->8 = BF det centers 1-8, 9->16 FF det centers. 17->18 segment scans, 19->20 cosmics
/Generator/EventShift 0 mm                        #Use to move the spawning location of primary events. Set usage in MOLLEROptPrimaryGeneratorAction.cc
/Generator/SegmentHitRegion 1                     #Select a section of the segment to fire the beam at. Currently only works if EventHitRegion = 10
/Generator/BeamSolidAngle 0                       #Units of degrees. Determines the angular spread of the beam from the z-axis. 18 for W&M setup
/Generator/BeamEnergy 8000		                  #Units of MeV. Does nothing if PrimaryParticle != 1
/Generator/BeamEnergyCut 0                        #Units of MeV. Sets minimum energy for primary particles (less than or equal is rejected)

/Storage/DetectorFocus 0                          #Controls what data is saved to the ROOT Ntuple. 0 for all detectors, 1 for Ring1, 2 for Ring2, etc. 999 saves nothing

#/RunAction/SetID 3
#/random/setSeeds 346082 823457
#/run/beamOn 1
